set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(EXECUTABLE_OUTPUT_PATH, bin)
set(LIBRARY_OUTPUT_PATH, lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY, bin)
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)

set(CMAKE_C_FLAGS " -DPLIBSYS_COMPILATION -DPLIBSYS_HAS_CLOCKNANOSLEEP -DPLIBSYS_HAS_GETADDRINFO -DPLIBSYS_HAS_LLDIV  -DPLIBSYS_HAS_NANOSLEEP -DPLIBSYS_HAS_POSIX_SCHEDULING -DPLIBSYS_HAS_POSIX_STACKSIZE -DPLIBSYS_HAS_PTHREAD_SETNAME -DPLIBSYS_HAS_SOCKADDR_STORAGE -DPLIBSYS_HAS_SOCKLEN_T  -DPLIBSYS_MMAP_HAS_MAP_ANONYMOUS -DPLIBSYS_SOCKADDR_IN6_HAS_FLOWINFO  -DPLIBSYS_SOCKADDR_IN6_HAS_SCOPEID -D_GNU_SOURCE -D_REENTRANT -Dplibsys_EXPORTS ")